# -*- coding: utf-8 -*-
"""ev.blast

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwmJI62b-ychu0uP1WoShDE-B-KuAn7-
"""

import streamlit as st
import pandas as pd
import joblib

st.title("EV Blast Prediction System")

# Model Load
model = joblib.load("model.pkl")   # apna model file name yaha likho

st.subheader("Enter Vehicle Details")

battery_temp = st.number_input("Battery Temperature", min_value=0.0)
voltage = st.number_input("Voltage", min_value=0.0)
current = st.number_input("Current", min_value=0.0)
charging_cycles = st.number_input("Charging Cycles", min_value=0)

if st.button("Predict"):

    input_data = pd.DataFrame({
        "battery_temp": [battery_temp],
        "voltage": [voltage],
        "current": [current],
        "charging_cycles": [charging_cycles]
    })

    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("High Risk of EV Blast")
    else:
        st.success("EV is Safe")
