# -*- coding: utf-8 -*-
"""ev.blast

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwmJI62b-ychu0uP1WoShDE-B-KuAn7-
"""

# First install required libraries:
# pip install gradio joblib pandas

import stremlit as st
import joblib
import pandas as pd

# Load trained model
model = joblib.load("dtc_model (1).pkl")

# Prediction function
def predict_wine(fixed_acidity, volatile_acidity, citric_acid, residual_sugar,
                 chlorides, free_sulfur_dioxide, total_sulfur_dioxide,
                 density, pH, sulphates, alcohol, quality):

    try:
        input_data = pd.DataFrame({
            "fixed_acidity": [fixed_acidity],
            "volatile_acidity": [volatile_acidity],
            "citric_acid": [citric_acid],
            "residual_sugar": [residual_sugar],
            "chlorides": [chlorides],
            "free_sulfur_dioxide": [free_sulfur_dioxide],
            "total_sulfur_dioxide": [total_sulfur_dioxide],
            "density": [density],
            "pH": [pH],
            "sulphates": [sulphates],
            "alcohol": [alcohol],
            "quality": [quality]
        })

        prediction = model.predict(input_data)[0]

        if prediction == "white":
            return "White Wine"
        else:
            return "Red Wine"

    except Exception as e:
        return f"Error: {str(e)}"

# Create Gradio interface
interface = gr.Interface(
    fn=predict_wine,
    inputs=[
        gr.Number(label="fixed_acidity"),
        gr.Number(label="volatile_acidity"),
        gr.Number(label="citric_acid"),
        gr.Number(label="residual_sugar"),
        gr.Number(label="chlorides"),
        gr.Number(label="free_sulfur_dioxide"),
        gr.Number(label="total_sulfur_dioxide"),
        gr.Number(label="density"),
        gr.Number(label="pH"),
        gr.Number(label="sulphates"),
        gr.Number(label="alcohol"),
        gr.Number(label="quality"),
    ],
    outputs=gr.Textbox(label="Prediction"),
    title="Wine Type Prediction"
)

# Launch app
if __name__ == "__main__":
    interface.launch()
